# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07d93e06232aa0804db007a39348cbc9cc5b59a08f0a9e77b5dc9487af87dbaae314fcea0c2379a49bcb800bfa52beede249e59eb86e158ac20f8b03ddd30742

test:
  secret_key_base: 49378ede8d4db48057923cb55fe9d8c1a1305a6bf8f819c187446b79e1a5d271766298951f472d9a6411075098099270b806177b28288628b8a025e92b671af6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
